definitions:
  auth_models.LoginRequest:
    properties:
      email:
        example: user@gmail.com
        type: string
      password:
        example: password
        type: string
    type: object
  auth_models.RegisterRequest:
    properties:
      email:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  helpers.ApiResponse:
    properties:
      data: {}
      message:
        type: string
    type: object
  helpers.ApiResponseAuthorization:
    properties:
      data: {}
      message:
        type: string
      token:
        type: string
    type: object
info:
  contact: {}
paths:
  /login:
    post:
      consumes:
      - application/json
      description: Login with email and password (only email gmail make used)
      parameters:
      - description: Login Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth_models.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/helpers.ApiResponseAuthorization'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
      summary: Login user
      tags:
      - Auth
  /register:
    post:
      consumes:
      - application/json
      description: Register with username, email, password (only email gmail make
        used)
      parameters:
      - description: Register Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth_models.RegisterRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/helpers.ApiResponse'
      summary: Register user
      tags:
      - Auth
swagger: "2.0"
